// signals/src/Counter.tsx
import { createSignal } from "solid-js";

interface CounterProps {
  startWith: number;
}

export const Counter = (props: CounterProps) => {
  const [counterSignal, setCounterSignal] = createSignal(props.startWith);

  console.log("Rendering in Solid");

  return (
    <div>
      <button onClick={(e) => setCounterSignal(counterSignal() + 1)}>+</button>
      <button onClick={(e) => setCounterSignal(counterSignal() - 1)}>-</button>
      <div>{counterSignal()}</div>
    </div>
  );
};

// react-counter/src/Counter.tsx
import { useState } from "react";

interface CounterProps {
  startWith: number;
}

export const Counter = ({ startWith }: CounterProps) => {
  const [counter, setCounter] = useState(startWith);

  console.log("Rendering in React");

  return (
    <div>
      <button onClick={(e) => setCounter(counter + 1)}>+</button>
      <button onClick={(e) => setCounter(counter - 1)}>-</button>
      <div>{counter}</div>
    </div>
  );
};
