// signalsAstro/src/components/reactCounter/Counter.tsx
import { useState } from "react";
interface CounterProps {
  startWith: number;
}

const Counter = ({ startWith }: CounterProps) => {
  const [counter, setCounter] = useState(startWith);

  //console.log("Rendering in React");

  return (
    <div className={"counter-wrapper"}>
      <button onClick={(e) => setCounter(counter + 1)}>+</button>
      <button onClick={(e) => setCounter(counter - 1)}>-</button>
      <div className    ={"counter-value"}>{counter}</div>
    </div>
  );
};

export default Counter;

// signalsAstro/src/components/solidCounter/Counter.tsx
import { createSignal } from "solid-js";
interface CounterProps {
  startWith: number;
}
const Counter = ({startWith}: CounterProps) => {
  const [counterSignal, setCounterSignal] = createSignal(startWith);

  console.log("Rendering in Solid");

  return (
    <div class="counter-wrapper">
      <button onClick={(e) => setCounterSignal(counterSignal() + 1)}>+</button>
      <button onClick={(e) => setCounterSignal(counterSignal() - 1)}>-</button>
      <div class="counter-value">{counterSignal()}</div>
    </div>
  );
};

export default Counter;
