// qwik/src/components/starter/counter/counter.tsx
import { component$, useSignal, useStylesScoped$ } from "@builder.io/qwik";
import styles from "./counter.css?inline";

export default component$(() => {
  useStylesScoped$(styles);
  const count = useSignal(10);
  console.log("Render");
  return (
    <div class="counter-wrapper">
      <button onClick$={() => count.value--}>-</button>
      <span class={`counter-value ${count.value % 2 === 0 ? "odd" : ""}`}>
        {count.value}
      </span>
      <button onClick$={() => count.value++}>+</button>
    </div>
  );
});

// signalsAstro/src/components/reactCounter/Counter.tsx
import { useState } from "react";
interface CounterProps {
  startWith: number;
}

const Counter = ({ startWith }: CounterProps) => {
  const [counter, setCounter] = useState(startWith);

  //console.log("Rendering in React");

  return (
    <div className={"counter-wrapper"}>
      <button onClick={(e) => setCounter(counter + 1)}>+</button>
      <button onClick={(e) => setCounter(counter - 1)}>-</button>
      <div className    ={"counter-value"}>{counter}</div>
    </div>
  );
};

export default Counter;
